server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: admin
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: teach-to-tech-article-service
          uri: lb://teach-to-tech-article-service
          predicates:
            - Path=/articles/**
          filters:
            - StripPrefix=0

        - id: teach-to-tech-notes-service
          uri: lb://teach-to-tech-notes-service
          predicates:
            - Path=/notes/**
          filters:
            - StripPrefix=0

        - id: teach-to-tech-trainer-service
          uri: lb://teach-to-tech-trainer-service
          predicates:
            - Path=/trainer/**
          filters:
            - StripPrefix=0

        - id: teach-to-tech-category-service
          uri: lb://teach-to-tech-category-service
          predicates:
             - Path=/category/**
          filters:
             - StripPrefix=0

  

  application:
    name: teach-to-tech-api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    gateway:
      enabled: true
    health:
      enabled: true
